// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHRUOrURhVtcv5Kh_p6YGOXGMXe1xUdDE',
    appId: '1:130467636176:web:648ae79423b8ed04a1cfd5',
    messagingSenderId: '130467636176',
    projectId: 'fbla-app-fda42',
    authDomain: 'fbla-app-fda42.firebaseapp.com',
    storageBucket: 'fbla-app-fda42.firebasestorage.app',
    measurementId: 'G-P56H40SW6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQR5qnDFEOAca4eqwtwQZFOn8OcbH0PBY',
    appId: '1:130467636176:android:b04405a54893bc68a1cfd5',
    messagingSenderId: '130467636176',
    projectId: 'fbla-app-fda42',
    storageBucket: 'fbla-app-fda42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZdJ5RhWAj_KvDikFXX52swrrbFmbo-E',
    appId: '1:130467636176:ios:b8e403331f5d0b66a1cfd5',
    messagingSenderId: '130467636176',
    projectId: 'fbla-app-fda42',
    storageBucket: 'fbla-app-fda42.firebasestorage.app',
    iosClientId: '130467636176-6fpkfpt6dv07kqgti69cjvl887lkjj00.apps.googleusercontent.com',
    iosBundleId: 'com.example.fblaApplication',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAAZdJ5RhWAj_KvDikFXX52swrrbFmbo-E',
  //   appId: '1:130467636176:ios:b8e403331f5d0b66a1cfd5',
  //   messagingSenderId: '130467636176',
  //   projectId: 'fbla-app-fda42',
  //   storageBucket: 'fbla-app-fda42.firebasestorage.app',
  //   iosBundleId: 'com.example.fblaApplication',
  // );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHRUOrURhVtcv5Kh_p6YGOXGMXe1xUdDE',
    appId: '1:130467636176:web:13ad8e59f133fc58a1cfd5',
    messagingSenderId: '130467636176',
    projectId: 'fbla-app-fda42',
    databaseURL: 'fbla-app-fda42.nam5.firebasedatabase.app',
    authDomain: 'fbla-app-fda42.firebaseapp.com',
    storageBucket: 'fbla-app-fda42.firebasestorage.app',
    // databaseURL: 'fbla-app-fda42.nam5.firebasedatabase.app',
    measurementId: 'G-PNX0DF9X6T',
  );
}